efault: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: my_app_user
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_app_development

test:
  <<: *default
  database: my_app_test

production:
  <<: *default
  database: my_app_production